In [2]:
import numpy as np

In [3]:
lista = [1, 2 , 3]

In [4]:
print(lista)

[1, 2, 3]


In [5]:
type(lista)

list

In [6]:
np.array(lista)

array([1, 2, 3])

In [7]:
a = np.array(lista)

In [8]:
type(a)

numpy.ndarray

In [9]:
lista = [ [1,2,3], [4,5,6], [7,8,9]]
np.array(lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
##Arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
#Linspace
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
#Rand
np.random.rand(5)


array([0.42496836, 0.70692056, 0.89126884, 0.2200161 , 0.1538224 ])

In [19]:
np.random.rand(5) * 100

array([96.46095936, 34.00289006, 56.4324015 , 59.2484595 , 32.28931026])

In [1]:
#Indexação Numpy

In [5]:
import numpy as np

In [9]:
arr = np.arange(0,21)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [13]:
arr[15]


15

In [15]:
arr [4:6]

array([4, 5])

In [21]:
arr[2:6] = 20

In [23]:
1 + 6

7